In [1]:
import pandas as pd

In [2]:
df_eda_p1 = pd.read_csv('./data/processed/eda_normalizado_p1v3.csv')
df_eda_p2 = pd.read_csv('./data/processed/eda_normalizado_p2v3.csv')
df_ppg_p1 = pd.read_csv('./data/processed/ppg_p1_v3.csv')
df_ppg_p2 = pd.read_csv('./data/processed/ppg_p2_v3.csv')

In [3]:
df_eda_p1['participant'].value_counts()

participant
S06    6
S07    6
S08    6
S09    6
S10    6
S12    6
S14    6
S15    6
S17    6
S18    6
S20    6
S21    6
S22    6
S23    6
S24    6
S26    6
S27    6
S28    6
S29    6
S30    6
S11    5
Name: count, dtype: int64

In [7]:
df_ppg_p1['participant'].value_counts()

participant
S06    6
S07    6
S08    6
S09    6
S10    6
S12    6
S14    6
S15    6
S17    6
S18    6
S20    6
S21    6
S22    6
S23    6
S24    6
S26    6
S27    6
S29    6
S30    6
S11    5
Name: count, dtype: int64

In [5]:
df_eda_p2

,Unnamed: 0,code,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,...,EDA_Phasic_std,SCR_Height_std,SCR_Amplitude_std,SCR_RiseTime_std,SCR_RecoveryTime_std,errors,event_duration_ms,participant,condition,secondary_task
0,0,1,4,4,4,0.399903,0.435013,0.196055,0.000000,0.0,...,0.071977,0.003161,0.002904,0.004073,0.003857,1.0,131647631,S104,V1P1,no
1,1,2,7,7,6,0.536965,0.596726,0.000000,0.000000,0.0,...,0.143732,0.007816,0.006488,0.004603,0.000323,0.0,138158072,S104,V1P2,no
2,2,3,3,3,3,0.437425,0.481298,0.312249,0.000000,0.0,...,0.069140,0.003304,0.002283,0.003509,0.004741,0.0,110122208,S104,V2P1,no
3,3,4,1,1,1,0.290711,0.314712,0.322205,0.000000,0.0,...,0.041183,0.001898,0.000662,0.002333,0.000136,0.0,126511836,S104,V2P2,no
4,4,5,9,9,9,0.444327,0.474695,0.278704,0.000000,0.0,...,0.089254,0.004286,0.002253,0.004976,0.000326,0.0,127925969,S104,V3P1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,7,8,0,0,0,0.000000,0.000000,0.168911,0.019215,0.0,...,0.013192,0.000000,0.000000,0.000000,0.000000,1.0,135837768,S134,V1P2,yes
296,8,9,0,0,1,0.224907,0.399645,0.201796,0.019215,0.0,...,0.016252,0.000000,0.000000,0.000000,0.004438,0.0,125277679,S134,V2P1,yes
297,9,10,9,9,8,0.137123,0.338533,0.059663,0.019215,0.0,...,0.063355,0.004352,0.004514,0.005096,0.001087,0.0,129859474,S134,V2P2,yes
298,10,11,1,1,1,0.100251,0.205238,0.151696,0.019215,0.0,...,0.015708,0.000544,0.000246,0.000410,0.000006,2.0,128559203,S134,V3P1,yes
299,11,12,3,3,2,0.378881,0.685109,0.175335,0.019215,0.0,...,0.025470,0.001901,0.002050,0.003956,0.000090,2.0,104497993,S134,V3P2,yes

In [6]:
df_ppg_p2

,code,PPG_Rate_min,PPG_Quality_min,HRV_MeanNN_min,HRV_MedianNN_min,HRV_SDNN_min,HRV_RMSSD_min,HRV_pNN50_min,HRV_LFHF_min,PPG_Rate_max,...,HRV_MeanNN_std,HRV_MedianNN_std,HRV_SDNN_std,HRV_RMSSD_std,HRV_pNN50_std,HRV_LFHF_std,event_duration_ms,participant,condition,secondary_task
0,1,0.207253,0.516913,0.890179,1.000000,0.030393,0.029938,0.113536,0.766485,0.473671,...,0.0,0.0,0.0,0.0,0.0,0.0,131647631,S104,V1P1,"27 no\nName: secondary_task, dtype: object"
1,2,0.234290,0.560530,0.652025,0.830769,0.015911,0.002424,0.064499,1.000000,0.530525,...,0.0,0.0,0.0,0.0,0.0,0.0,138158072,S104,V1P2,"33 no\nName: secondary_task, dtype: object"
2,3,0.234290,0.446784,0.383021,0.646154,0.000000,0.000000,0.000000,0.253563,0.494626,...,0.0,0.0,0.0,0.0,0.0,0.0,110122208,S104,V2P1,"30 no\nName: secondary_task, dtype: object"
3,4,0.210381,0.342562,0.630710,0.753846,0.159522,0.241924,0.650326,0.032674,0.487469,...,0.0,0.0,0.0,0.0,0.0,0.0,126511836,S104,V2P2,"21 no\nName: secondary_task, dtype: object"
4,5,0.229206,0.316233,0.534272,0.769231,0.139861,0.209425,0.646197,0.084006,0.617477,...,0.0,0.0,0.0,0.0,0.0,0.0,127925969,S104,V3P1,"24 no\nName: secondary_task, dtype: object"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,8,0.089238,0.037719,0.000000,0.000000,0.557054,0.687160,0.975200,0.036004,0.763730,...,0.0,0.0,0.0,0.0,0.0,0.0,135837768,S134,V1P2,"0 yes\nName: secondary_task, dtype: object"
296,9,0.099697,0.000000,0.370371,0.500000,0.236483,0.290838,0.296633,0.021388,0.911750,...,0.0,0.0,0.0,0.0,0.0,0.0,125277679,S134,V2P1,"6 yes\nName: secondary_task, dtype: object"
297,10,0.112717,0.241210,0.091705,0.150000,0.250073,0.396528,0.243074,0.000000,0.695962,...,0.0,0.0,0.0,0.0,0.0,0.0,129859474,S134,V2P2,"9 yes\nName: secondary_task, dtype: object"
298,11,0.203213,0.167746,0.090300,0.200000,0.020174,0.071192,0.162394,0.163637,0.637331,...,0.0,0.0,0.0,0.0,0.0,0.0,128559203,S134,V3P1,"15 yes\nName: secondary_task, dtype: object"
299,12,0.091655,0.198438,0.601329,0.675000,0.327868,0.344669,0.870308,0.107769,0.782355,...,0.0,0.0,0.0,0.0,0.0,0.0,104497993,S134,V3P2,"12 yes\nName: secondary_task, dtype: object"

In [10]:
df_eda_p2['participant'].value_counts()

participant
S104    12
S105    12
S106    12
S107    12
S108    12
S109    12
S110    12
S111    12
S112    12
S113    12
S117    12
S119    12
S120    12
S121    12
S122    12
S123    12
S124    12
S125    12
S128    12
S129    12
S130    12
S131    12
S132    12
S133    12
S134    12
Name: count, dtype: int64

In [11]:
df_ppg_p2['participant'].value_counts()

participant
S104    12
S105    12
S106    12
S107    12
S108    12
S109    12
S110    12
S111    12
S112    12
S113    12
S117    12
S119    12
S120    12
S121    12
S122    12
S123    12
S124    12
S125    12
S128    12
S129    12
S130    12
S131    12
S132    12
S133    12
S134    12
Name: count, dtype: int64

In [ ]:
# TODO: Unir os dfs em um df só

In [9]:
df.drop(['Unnamed: 0', 'code'], inplace=True, axis=1)
df.columns

Index(['SCR_Onsets', 'SCR_Peaks', 'SCR_Recovery', 'EDA_Clean_min',
       'EDA_Tonic_min', 'EDA_Phasic_min', 'SCR_Height_min',
       'SCR_Amplitude_min', 'SCR_RiseTime_min', 'SCR_RecoveryTime_min',
       'EDA_Clean_max', 'EDA_Tonic_max', 'EDA_Phasic_max', 'SCR_Height_max',
       'SCR_Amplitude_max', 'SCR_RiseTime_max', 'SCR_RecoveryTime_max',
       'EDA_Clean_median', 'EDA_Tonic_median', 'EDA_Phasic_median',
       'SCR_Height_median', 'SCR_Amplitude_median', 'SCR_RiseTime_median',
       'SCR_RecoveryTime_median', 'EDA_Clean_mean', 'EDA_Tonic_mean',
       'EDA_Phasic_mean', 'SCR_Height_mean', 'SCR_Amplitude_mean',
       'SCR_RiseTime_mean', 'SCR_RecoveryTime_mean', 'EDA_Clean_std',
       'EDA_Tonic_std', 'EDA_Phasic_std', 'SCR_Height_std',
       'SCR_Amplitude_std', 'SCR_RiseTime_std', 'SCR_RecoveryTime_std',
       'errors', 'errors_rate', 'event_duration_ms', 'participant',
       'condition', 'secondary_task'],
      dtype='str')

In [10]:
df['speed'] = df['condition'].str[:2]
df['position'] = df['condition'].str[2:]

In [11]:
df.shape

(425, 46)

In [12]:
df.describe()

,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,SCR_RiseTime_min,SCR_RecoveryTime_min,...,EDA_Clean_std,EDA_Tonic_std,EDA_Phasic_std,SCR_Height_std,SCR_Amplitude_std,SCR_RiseTime_std,SCR_RecoveryTime_std,errors,errors_rate,event_duration_ms
count,425.000000,425.000000,425.000000,425.000000,425.000000,425.000000,407.000000,407.0,407.0,425.0,...,425.000000,425.000000,425.000000,407.000000,407.000000,407.000000,425.000000,425.000000,125.000000,4.250000e+02
mean,6.327059,6.425882,6.331765,0.337978,0.384094,0.248929,0.030920,0.0,0.0,0.0,...,0.057847,0.061079,0.062544,0.003321,0.003015,0.004313,0.001633,1.985882,32.342857,1.288633e+08
std,5.623724,5.673073,5.575431,0.238691,0.254343,0.173077,0.064053,0.0,0.0,0.0,...,0.040280,0.046651,0.036275,0.002308,0.002284,0.002869,0.001809,3.817757,35.031878,1.835733e+07
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.002259,0.002832,0.001126,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.551015e+07
25%,2.000000,2.000000,2.000000,0.142023,0.184028,0.119706,0.000000,0.0,0.0,0.0,...,0.030683,0.028195,0.032492,0.001472,0.001005,0.001792,0.000172,0.000000,0.000000,1.245187e+08
50%,5.000000,5.000000,5.000000,0.322223,0.371223,0.240088,0.000000,0.0,0.0,0.0,...,0.048203,0.048943,0.059032,0.003089,0.002852,0.004386,0.000931,0.000000,16.666667,1.283064e+08
75%,9.000000,10.000000,10.000000,0.516419,0.578630,0.343609,0.042695,0.0,0.0,0.0,...,0.073827,0.079820,0.086924,0.004883,0.004701,0.006479,0.002489,2.000000,62.500000,1.345976e+08
max,39.000000,39.000000,38.000000,0.925814,0.957100,0.736150,0.391077,0.0,0.0,0.0,...,0.321517,0.321847,0.179568,0.010181,0.012774,0.010998,0.007749,21.000000,100.000000,3.990459e+08

In [13]:
df.tail(10)

,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,SCR_RiseTime_min,SCR_RecoveryTime_min,...,SCR_RiseTime_std,SCR_RecoveryTime_std,errors,errors_rate,event_duration_ms,participant,condition,secondary_task,speed,position
290,2,2,3,0.301590,0.535337,0.133718,0.019215,0.0,0.0,0.0,...,0.002751,0.000271,0.0,NaN,121537237,S134,V2P1,no,V2,P1
291,0,0,0,0.112202,0.206194,0.224090,0.019215,0.0,0.0,0.0,...,0.000000,0.000000,0.0,NaN,130217234,S134,V2P2,no,V2,P2
292,0,0,0,0.281280,0.503946,0.208773,0.019215,0.0,0.0,0.0,...,0.000000,0.000000,0.0,NaN,123797293,S134,V3P1,no,V3,P1
293,3,3,3,0.324109,0.573273,0.119706,0.019215,0.0,0.0,0.0,...,0.000534,0.000620,0.0,NaN,124498010,S134,V3P2,no,V3,P2
294,4,5,4,0.048669,0.418544,0.000000,0.000000,0.0,0.0,0.0,...,0.004932,0.000557,0.0,NaN,133259429,S134,V1P1,yes,V1,P1
295,0,0,0,0.000000,0.000000,0.168911,0.019215,0.0,0.0,0.0,...,0.000000,0.000000,1.0,NaN,135837768,S134,V1P2,yes,V1,P2
296,0,0,1,0.224907,0.399645,0.201796,0.019215,0.0,0.0,0.0,...,0.000000,0.004438,0.0,NaN,125277679,S134,V2P1,yes,V2,P1
297,9,9,8,0.137123,0.338533,0.059663,0.019215,0.0,0.0,0.0,...,0.005096,0.001087,0.0,NaN,129859474,S134,V2P2,yes,V2,P2
298,1,1,1,0.100251,0.205238,0.151696,0.019215,0.0,0.0,0.0,...,0.000410,0.000006,2.0,NaN,128559203,S134,V3P1,yes,V3,P1
299,3,3,2,0.378881,0.685109,0.175335,0.019215,0.0,0.0,0.0,...,0.003956,0.000090,2.0,NaN,104497993,S134,V3P2,yes,V3,P2

In [17]:
print(df['participant'].value_counts().min())
df['participant'].value_counts().idxmin()

5

'S11'

In [18]:
df[df['participant'] == 'S11']

,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,SCR_RiseTime_min,SCR_RecoveryTime_min,...,SCR_Height_std,SCR_Amplitude_std,SCR_RiseTime_std,SCR_RecoveryTime_std,event_duration_ms,participant,condition,secondary_task,speed,position
30,17,17,17,0.284390,0.342017,0.149154,0.074141,0.0,0.0,0.0,...,0.005321,0.003966,0.005909,0.000737,123137787,S11,V1P1,no,V1,P1
31,11,12,12,0.145577,0.044128,0.276194,0.156146,0.0,0.0,0.0,...,0.003758,0.003603,0.005536,0.000665,125756340,S11,V1P2,no,V1,P2
32,10,11,11,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.005878,0.004670,0.007102,0.000553,125598657,S11,V2P1,no,V2,P1
33,39,39,38,0.047639,0.044061,0.033943,0.156146,0.0,0.0,0.0,...,0.005123,0.004700,0.004740,0.002640,399045906,S11,V2P2,no,V2,P2
34,19,20,20,0.522646,0.588925,0.213969,0.156146,0.0,0.0,0.0,...,0.005293,0.004699,0.005938,0.000601,148778254,S11,V3P2,no,V3,P2

In [10]:
print('V1')
display(df[df['speed'] == 'V1'].describe())
print('V2')
display(df[df['speed'] == 'V2'].describe())
print('V3')
display(df[df['speed'] == 'V3'].describe())

V1

,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,SCR_RiseTime_min,SCR_RecoveryTime_min,...,SCR_RiseTime_mean,SCR_RecoveryTime_mean,EDA_Clean_std,EDA_Tonic_std,EDA_Phasic_std,SCR_Height_std,SCR_Amplitude_std,SCR_RiseTime_std,SCR_RecoveryTime_std,event_duration_ms
count,142.000000,142.000000,142.000000,138.000000,138.000000,138.000000,132.000000,132.0,132.0,138.0,...,132.000000,138.000000,138.000000,138.000000,138.000000,132.000000,132.000000,132.000000,138.000000,1.420000e+02
mean,5.669014,5.802817,5.683099,0.313784,0.356755,0.257248,0.031948,0.0,0.0,0.0,...,0.000046,0.000015,0.056097,0.059853,0.059553,0.003130,0.002930,0.004306,0.001845,1.306114e+08
std,4.553421,4.606870,4.527880,0.228696,0.240854,0.171519,0.060331,0.0,0.0,0.0,...,0.000041,0.000019,0.037601,0.045766,0.034804,0.002123,0.002111,0.002682,0.001960,1.353135e+07
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.000000,0.000000,0.005397,0.005320,0.006026,0.000000,0.000000,0.000000,0.000000,3.551015e+07
25%,2.000000,2.000000,2.000000,0.120836,0.175181,0.146278,0.000000,0.0,0.0,0.0,...,0.000013,0.000001,0.028041,0.026532,0.032905,0.001516,0.001139,0.002059,0.000172,1.220436e+08
50%,5.000000,5.000000,5.000000,0.313356,0.360389,0.239617,0.000000,0.0,0.0,0.0,...,0.000033,0.000008,0.047345,0.045687,0.052674,0.002865,0.002722,0.004388,0.001080,1.340628e+08
75%,8.000000,8.000000,9.000000,0.462876,0.529210,0.342269,0.053656,0.0,0.0,0.0,...,0.000077,0.000021,0.074913,0.081750,0.081620,0.004517,0.004428,0.006416,0.003270,1.384170e+08
max,19.000000,19.000000,19.000000,0.925814,0.957100,0.698464,0.391077,0.0,0.0,0.0,...,0.000174,0.000093,0.190288,0.209599,0.153529,0.009303,0.009678,0.010151,0.007388,1.832519e+08

V2

,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,SCR_RiseTime_min,SCR_RecoveryTime_min,...,SCR_RiseTime_mean,SCR_RecoveryTime_mean,EDA_Clean_std,EDA_Tonic_std,EDA_Phasic_std,SCR_Height_std,SCR_Amplitude_std,SCR_RiseTime_std,SCR_RecoveryTime_std,event_duration_ms
count,142.000000,142.000000,142.000000,138.000000,138.000000,138.000000,132.000000,132.0,132.0,138.0,...,132.000000,1.380000e+02,138.000000,138.000000,138.000000,132.000000,132.000000,132.000000,138.000000,1.420000e+02
mean,6.197183,6.281690,6.246479,0.313691,0.354390,0.253167,0.033339,0.0,0.0,0.0,...,0.000045,1.235887e-05,0.055460,0.058568,0.059439,0.003111,0.002759,0.003923,0.001406,1.295928e+08
std,6.279811,6.315989,6.250318,0.242139,0.258168,0.184018,0.067053,0.0,0.0,0.0,...,0.000046,1.901296e-05,0.035771,0.043239,0.035534,0.002397,0.002307,0.002939,0.001646,2.690456e+07
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.000000,0.000000e+00,0.005804,0.006454,0.004441,0.000000,0.000000,0.000000,0.000000,3.819382e+07
25%,1.000000,1.000000,1.000000,0.106791,0.127046,0.106913,0.000000,0.0,0.0,0.0,...,0.000006,6.282577e-07,0.030283,0.028546,0.029252,0.001284,0.000730,0.001044,0.000105,1.255674e+08
50%,4.000000,4.000000,4.000000,0.278179,0.324491,0.250734,0.000000,0.0,0.0,0.0,...,0.000031,6.780742e-06,0.047416,0.049323,0.053326,0.002715,0.002413,0.003802,0.000800,1.283773e+08
75%,9.000000,9.000000,9.000000,0.496734,0.567605,0.362190,0.046188,0.0,0.0,0.0,...,0.000061,1.714645e-05,0.072482,0.077423,0.084521,0.004732,0.004291,0.005985,0.002015,1.311051e+08
max,39.000000,39.000000,38.000000,0.815669,0.852124,0.736150,0.391077,0.0,0.0,0.0,...,0.000173,1.117625e-04,0.228296,0.240485,0.138078,0.010181,0.009930,0.009809,0.007137,3.990459e+08

V3

,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,SCR_RiseTime_min,SCR_RecoveryTime_min,...,SCR_RiseTime_mean,SCR_RecoveryTime_mean,EDA_Clean_std,EDA_Tonic_std,EDA_Phasic_std,SCR_Height_std,SCR_Amplitude_std,SCR_RiseTime_std,SCR_RecoveryTime_std,event_duration_ms
count,141.000000,141.000000,141.000000,137.000000,137.000000,137.000000,131.000000,131.0,131.0,137.0,...,131.000000,137.000000,137.000000,137.000000,137.000000,131.000000,131.000000,131.000000,137.000000,1.410000e+02
mean,7.120567,7.198582,7.070922,0.388204,0.443070,0.230759,0.030278,0.0,0.0,0.0,...,0.000057,0.000015,0.061571,0.063937,0.067930,0.003701,0.003247,0.004647,0.001650,1.263682e+08
std,5.838879,5.907888,5.759024,0.244499,0.259175,0.166181,0.067226,0.0,0.0,0.0,...,0.000051,0.000022,0.047803,0.052029,0.038651,0.002433,0.002420,0.002991,0.001847,9.862165e+06
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.000000,0.000000,0.002259,0.002832,0.001126,0.000000,0.000000,0.000000,0.000000,8.161258e+07
25%,2.000000,2.000000,2.000000,0.206023,0.261108,0.108918,0.000000,0.0,0.0,0.0,...,0.000014,0.000001,0.031847,0.029246,0.034894,0.001604,0.001009,0.002138,0.000190,1.239973e+08
50%,6.000000,6.000000,6.000000,0.368420,0.450850,0.214857,0.000000,0.0,0.0,0.0,...,0.000042,0.000007,0.049362,0.048943,0.066356,0.003871,0.003276,0.004737,0.000961,1.267176e+08
75%,11.000000,11.000000,11.000000,0.545625,0.643040,0.322142,0.032442,0.0,0.0,0.0,...,0.000090,0.000021,0.073827,0.079645,0.092405,0.005478,0.004855,0.006956,0.002489,1.292794e+08
max,26.000000,26.000000,24.000000,0.890167,0.929047,0.708427,0.391077,0.0,0.0,0.0,...,0.000230,0.000141,0.321517,0.321847,0.179568,0.009177,0.012774,0.010998,0.007749,1.746394e+08

In [11]:
print('P1')
display(df[df['position'] == 'P1'].describe())
print('P2')
display(df[df['position'] == 'P2'].describe())

P1

,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,SCR_RiseTime_min,SCR_RecoveryTime_min,...,SCR_RiseTime_mean,SCR_RecoveryTime_mean,EDA_Clean_std,EDA_Tonic_std,EDA_Phasic_std,SCR_Height_std,SCR_Amplitude_std,SCR_RiseTime_std,SCR_RecoveryTime_std,event_duration_ms
count,212.000000,212.000000,212.000000,206.000000,206.000000,206.000000,197.000000,197.0,197.0,206.0,...,197.000000,2.060000e+02,206.000000,206.000000,206.000000,197.000000,197.000000,197.000000,206.000000,2.120000e+02
mean,6.146226,6.235849,6.183962,0.345485,0.394551,0.244204,0.030323,0.0,0.0,0.0,...,0.000048,1.406143e-05,0.058716,0.061346,0.062579,0.003277,0.002933,0.004214,0.001634,1.275855e+08
std,5.363766,5.432135,5.332466,0.240064,0.251664,0.175199,0.062419,0.0,0.0,0.0,...,0.000047,2.019576e-05,0.043933,0.049015,0.036102,0.002300,0.002292,0.002914,0.001885,1.309242e+07
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.000000,0.000000e+00,0.002259,0.002832,0.001126,0.000000,0.000000,0.000000,0.000000,3.819382e+07
25%,2.000000,2.000000,2.000000,0.141183,0.187358,0.124290,0.000000,0.0,0.0,0.0,...,0.000011,8.685175e-07,0.029686,0.027203,0.032685,0.001312,0.000878,0.001566,0.000152,1.236519e+08
50%,5.000000,5.000000,4.500000,0.349822,0.414997,0.224360,0.000000,0.0,0.0,0.0,...,0.000034,6.371924e-06,0.048100,0.049315,0.059793,0.003161,0.002584,0.004353,0.000723,1.273671e+08
75%,9.000000,9.000000,9.000000,0.522159,0.570809,0.340306,0.042695,0.0,0.0,0.0,...,0.000075,2.015776e-05,0.075201,0.079626,0.088716,0.004871,0.004742,0.006426,0.002852,1.309742e+08
max,26.000000,26.000000,24.000000,0.925814,0.957100,0.736150,0.391077,0.0,0.0,0.0,...,0.000230,1.411393e-04,0.321517,0.321847,0.148525,0.010119,0.012774,0.010998,0.007749,2.081974e+08

P2

,SCR_Onsets,SCR_Peaks,SCR_Recovery,EDA_Clean_min,EDA_Tonic_min,EDA_Phasic_min,SCR_Height_min,SCR_Amplitude_min,SCR_RiseTime_min,SCR_RecoveryTime_min,...,SCR_RiseTime_mean,SCR_RecoveryTime_mean,EDA_Clean_std,EDA_Tonic_std,EDA_Phasic_std,SCR_Height_std,SCR_Amplitude_std,SCR_RiseTime_std,SCR_RecoveryTime_std,event_duration_ms
count,213.000000,213.000000,213.000000,207.000000,207.000000,207.000000,198.000000,198.0,198.0,207.0,...,198.000000,207.000000,207.000000,207.000000,207.000000,198.000000,198.000000,198.000000,207.000000,2.130000e+02
mean,6.507042,6.615023,6.478873,0.331428,0.374691,0.249976,0.033388,0.0,0.0,0.0,...,0.000050,0.000014,0.056688,0.060213,0.062010,0.003349,0.003024,0.004367,0.001633,1.301352e+08
std,5.878181,5.909870,5.816030,0.241364,0.259676,0.173280,0.067190,0.0,0.0,0.0,...,0.000045,0.000020,0.037311,0.045194,0.036960,0.002367,0.002285,0.002854,0.001771,2.236341e+07
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,...,0.000000,0.000000,0.005397,0.005320,0.004257,0.000000,0.000000,0.000000,0.000000,3.551015e+07
25%,2.000000,2.000000,2.000000,0.145641,0.176680,0.111721,0.000000,0.0,0.0,0.0,...,0.000013,0.000001,0.030006,0.028492,0.031559,0.001525,0.001005,0.002071,0.000166,1.256588e+08
50%,5.000000,5.000000,5.000000,0.290711,0.332168,0.240088,0.000000,0.0,0.0,0.0,...,0.000035,0.000008,0.047813,0.046528,0.056675,0.002964,0.002871,0.004388,0.000972,1.298595e+08
75%,10.000000,10.000000,10.000000,0.515660,0.589130,0.343521,0.043699,0.0,0.0,0.0,...,0.000079,0.000020,0.072486,0.078853,0.084874,0.005018,0.004492,0.006483,0.002386,1.354778e+08
max,39.000000,39.000000,38.000000,0.882401,0.929047,0.709322,0.391077,0.0,0.0,0.0,...,0.000187,0.000124,0.229937,0.240485,0.179568,0.010181,0.009930,0.010072,0.007388,3.990459e+08

In [ ]:
# TODO: Ver para cada variável para cada participante a correlação com a quantidade de erros